services:
  db:
    image: postgis/postgis:16-3.4
    container_name: deserttrash_db
    environment:
      POSTGRES_DB: deserttrash
      POSTGRES_USER: deserttrash
      POSTGRES_PASSWORD: deserttrash_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
